apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Workflow evidence item post'
description: 'Action for posting workflow evidence item from a workflow step'

inputs:
  content:
    description: Information to capture as an evidence item for the workflow run. The information is captured at the step level for the workflow run.
  format:
    description: Used to render the evidence item.
    default: markdown

runs:
  using: composite
  steps:
    - id: postWorkflowEvidenceItem
      name: Post workflow evidence item
      uses: docker://alpine/curl:latest
      run: |
        curl -X 'POST' "$URL/v1/workflows/artifact" -H "Authorization: Bearer $JWT" -H 'Content-Type: application/json' --data-binary '{"stepId": "'"$STEP_ID"'", "evidence": {"value": "'"$CONTENT"'", "format": "'"$FORMAT"'"}}'
      env:
        STEP_ID: $${{ step.id }}
        CONTENT: ${{ inputs.content }}
        FORMAT: ${{ inputs.format }}
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
