apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Publish evidence item'
description: 'Use this action to capture information that serves as evidence of work done by the workflow run.'

inputs:
  content:
    description: Information to capture as an evidence item for the workflow run. The information is captured at the step level for the workflow run.
    required: true
  format:
    description: Used to render the evidence item.
    default: MARKDOWN

runs:
  using: composite
  steps:
    - id: postWorkflowEvidenceItem
      name: Post workflow evidence item
      uses: docker://alpine/curl:latest
      run: |
        # Prepare content to be used in the JSON
        PREPARED_CONTENT=$(echo "$CONTENT" | sed 's/"/\\"/g' | sed 's/$/\\n/g' | tr -d '\n')
        
        # Make Platform API call to post workflow evidence item
        response=$(curl --fail-with-body  -X 'POST' "$URL/v1/workflows/artifact" -H "Authorization: Bearer $JWT" -H 'Content-Type: application/json' --data-binary '{"stepId": "'"$STEP_ID"'", "evidence": {"value": "'"$PREPARED_CONTENT"'", "format": "'"$FORMAT"'"}}') || command_failed=1
        
        # Check curl exit code
        if [ ${command_failed:-0} -eq 1 ];
        then
          echo "Platform API call failed with error: '$response'"
          exit 1
        fi
      env:
        STEP_ID: ${{ step.id }}
        CONTENT: ${{ inputs.content }}
        FORMAT: ${{ inputs.format }}
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
