apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Instrumented action example'
description: 'Illustrates how to instrument an exiting action definition to publish evidence to the workflow run'

inputs:
  input1:
    required: true
    description: One of the parameters of the original action
outputs:
  results-url:
    value: ${{ steps.do-something.outputs.url }}

runs:
  using: composite
  steps:
    - name: Do something
      id: do-something
      uses: docker://alpine:3.23.2
      shell: sh
      run: |
        echo "https://example.com" > "$CLOUDBEES_OUTPUTS/url"
        echo "Using the input parameter input1. Value: ${{ inputs.input1 }}"
          
    - name: Test publish-evidence-item action
      uses: cloudbees-io/publish-evidence-item
      with:
        content: |
          # Sample instrumented action example
          - Action parameter input1, value: ${{ inputs.input1 }}
          - [Instrumented action results URL](${{ steps.do-something.outputs.url }})
