apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Call instrumented action
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Call instrumented action
        uses: ./instrumented-action-example
        with:
          input1: Input to the action to illustrate passing data into evidence
