apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publish-evidence-item

on:
  push:
    branches:
      - '**'

permissions:
  id-token: read

jobs:
  testAction:
    steps:
    - id: testAction
      name: Test publish-evidence-item action
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: |
          ## Test markup and property rendering
          - Step ID: ${{ step.id }}
          - Color test: <span style="color:green">This text should be green</span>
        format: MARKDOWN
